"""Qian (2009) nested Latin hypercube design — algebraic construction.

Multi-layer construction strategy
----------------------------------
Qian (2009) defines the two-layer construction directly: given m < n, build a
vector π of length n whose first m entries τ form a valid m-layer LHD and all n
entries form a valid n-layer LHD.  Each column of the design is generated
*independently* via a circulant-matrix walk on the lcm grid.

For L > 2 layers [n_1, n_2, ..., n_L] we apply the two-layer construction
consecutively:

  Step 1: Build a two-layer (n_1, n_2) design column-by-column.
           Result: X of shape (n_2, k).  Rows 0..n_1-1 are the n_1-layer.

  Step 2: For each subsequent pair (n_i, n_{i+1}):
           - Take the existing n_i rows (rows 0..n_i-1 of the current design).
           - Build a fresh two-layer (n_i, n_{i+1}) design, where the FIRST n_i
             rows are the inner layer.
           - Append the n_{i+1} - n_i new complement rows to the design.
           - Track which rows of the growing (n_L, k) integer matrix belong to
             each layer via explicit index sets.

  Step 3: Convert to continuous coordinates once: (X_int + u) / n_L where u is
          drawn once for the full (n_L, k) shape and reused for all layers.

Column independence is preserved: each column is generated by an independent
call to _build_qian_column at each two-layer step.  No row_perm coupling across
columns is applied — joint uniformity comes from the probabilistic properties of
the circulant walk (Proposition 2.1 in Qian 2009), not from cross-column
coupling which would introduce negative correlation artefacts.
"""

from __future__ import annotations

import numpy as np
from math import gcd

from .validate import validate_m_layers_qian, validate_result
from .utils import random_integer_lhd


# ---------------------------------------------------------------------------
# Core two-layer primitive (one column)
# ---------------------------------------------------------------------------

def _build_qian_column(
    m: int,
    n: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Build one column of a two-layer nested design following Qian (2009) Section 2.

    Constructs a vector π of length n on integer levels {0, ..., n-1} such that:
      - The first m entries τ form a valid m-layer: one entry per stratum
        {0, ..., m-1} (i.e. floor(τ_i * m / n) are a permutation of {0..m-1}).
      - All n entries form a valid n-layer: one entry per level {0, ..., n-1}.

    Internally works on the 1-indexed lcm grid {1, ..., l} where l = lcm(m, n),
    then converts to 0-indexed {0, ..., n-1} for the output.

    Parameters
    ----------
    m : int
        Inner layer size.
    n : int
        Outer layer size.  Must be a multiple of m (Qian divisibility).
    rng : np.random.Generator

    Returns
    -------
    np.ndarray of shape (n,) dtype int64
        First m entries are the inner layer (levels in {0, ..., n-1} that each
        fall in a distinct coarse stratum of width n/m).
        All n entries are a permutation of {0, ..., n-1}.
    """
    l = (m * n) // gcd(m, n)    # lcm(m, n)
    n_prime = l // m             # = n / gcd(m,n) ... since n%m==0, n_prime = n//m = c
    m_prime = l // n             # = m / gcd(m,n) ... since n%m==0, m_prime = 1

    # ------------------------------------------------------------------
    # Step 1: circulant walk v of length m on {1, ..., n'}
    # M_{m', n'} is (n' - m' + 1) x n' circulant matrix.
    # Row r of M (0-indexed) applied to column index col (1-indexed):
    #   M[r, col] = ((col - 1 + r) % n') + 1
    # ------------------------------------------------------------------
    n_rows_circulant = n_prime - m_prime + 1   # number of rows in M
    v = np.zeros(m, dtype=np.int64)
    v[0] = rng.integers(1, n_prime + 1)        # uniform on {1, ..., n'}
    for i in range(1, m):
        r = rng.integers(0, n_rows_circulant)  # random row of M
        v[i] = ((v[i - 1] - 1 + r) % n_prime) + 1

    # ------------------------------------------------------------------
    # Step 2: build τ on {1, ..., l}
    # Pool: {v(i) + n'*(i-1) : i = 1..m} (1-indexed i)
    # Randomly permute the pool to get τ.
    # ------------------------------------------------------------------
    tau_pool = np.array([v[i] + n_prime * i for i in range(m)], dtype=np.int64)
    tau = rng.permutation(tau_pool)

    # S = {1, ..., n} \ {ceil(τ(i) / m') : i = 1..m}
    # Since m_prime = 1 when n % m == 0, ceil(τ(i) / 1) = τ(i).
    # But τ(i) are on the l-scale; coarse index = ceil(τ(i) / n') in {1..m}
    # and fine index for n-layer = ceil(τ(i) / m') = τ(i) since m'=1.
    # We need the n-scale strata occupied by τ:
    #   n-stratum of value x on l-scale = ceil(x / m') - 1  (0-indexed)
    #   = ceil(x / 1) - 1 = x - 1   when m_prime = 1
    # Since m_prime may not always be 1 for non-divisible cases, keep general:
    used_n_strata = set(int(np.ceil(t / m_prime)) - 1 for t in tau)
    S = [s for s in range(n) if s not in used_n_strata]  # 0-indexed free n-strata

    # ------------------------------------------------------------------
    # Step 3: build ρ on {1, ..., l} for the n - m complement entries
    # ρ(i) = t(i) + m' * s_i  where t(i) ~ Uniform{1..m'}, s_i = S[i] (0-indexed)
    # On the l-scale: s_i (0-indexed n-stratum) → 1-indexed = s_i + 1
    #   ρ(i) = t(i) + m' * s_i   (using 0-indexed s_i and 1-indexed t and l-values)
    # Check: ceil(ρ(i) / m') = s_i + 1 → n-stratum index s_i ✓
    # ------------------------------------------------------------------
    assert len(S) == n - m, f"S has wrong size: {len(S)} != {n - m}"
    rho_pool = np.array([
        rng.integers(1, m_prime + 1) + m_prime * S[i]
        for i in range(n - m)
    ], dtype=np.int64)
    rho = rng.permutation(rho_pool)

    # ------------------------------------------------------------------
    # Convert from l-scale {1, ..., l} to n-scale {0, ..., n-1}
    # n-stratum of l-value x = ceil(x / m') - 1  (0-indexed)
    # Within each n-stratum there are m' l-values; since m'=1 when n%m==0,
    # there is exactly one l-value per n-stratum, so the mapping is injective.
    # ------------------------------------------------------------------
    tau_n = np.array([int(np.ceil(t / m_prime)) - 1 for t in tau], dtype=np.int64)
    rho_n = np.array([int(np.ceil(r / m_prime)) - 1 for r in rho], dtype=np.int64)

    # Stack: inner layer first, then complement
    return np.concatenate([tau_n, rho_n])


# ---------------------------------------------------------------------------
# Two-layer design (all columns)
# ---------------------------------------------------------------------------

def _two_layer_qian(
    m: int,
    n: int,
    k: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Build a two-layer nested integer design of shape (n, k).

    Rows 0..m-1 form the inner m-layer (each column a permutation of
    coarse strata {0..m-1} mapped to {0..n-1}).
    All n rows form the outer n-layer (each column a permutation of {0..n-1}).
    Columns are generated independently (no cross-column coupling).

    Parameters
    ----------
    m, n : inner and outer layer sizes; n must be a multiple of m.
    k : number of dimensions.
    rng : random generator.

    Returns
    -------
    np.ndarray of shape (n, k), dtype int64, values in {0, ..., n-1}.
    """
    X = np.zeros((n, k), dtype=np.int64)
    for j in range(k):
        X[:, j] = _build_qian_column(m, n, rng)
    return X


# ---------------------------------------------------------------------------
# Multi-layer assembly
# ---------------------------------------------------------------------------

def _build_multilayer_integer(
    m_layers: list[int],
    k: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, dict[int, list[int]]]:
    """
    Build the full integer design for all layers on the finest grid {0..n_L-1}.

    For each consecutive pair (n_{i-1}, n_i):
      1. Build a fresh two-layer design on the n_i grid {0..n_i-1}.
      2. The inner layer (rows 0..n_{i-1}-1) tells us which n_i-grid slots
         the existing inner points land in — but we do NOT use these rows
         directly.  Instead we re-embed the existing inner rows from the
         accumulating design by multiplying by c = n_i // n_{i-1}.
      3. Only the complement rows (rows n_{i-1}..n_i-1) from the fresh
         two-layer design are new.  We keep their relative positions within
         the n_i grid, then re-scale to n_L at the end.

    To keep things consistent, we maintain all coordinates on the CURRENT
    layer's grid {0..n_i-1} during assembly, then do a single final
    re-scaling to {0..n_L-1} at the end.
    """
    n_L = m_layers[-1]
    layer_indices: dict[int, list[int]] = {}

    # --- Step 1: first two layers ---
    n1, n2 = m_layers[0], m_layers[1]
    X_current = _two_layer_qian(n1, n2, k, rng)  # shape (n2, k), values {0..n2-1}

    layer_indices[n1] = list(range(n1))
    layer_indices[n2] = list(range(n2))
    n_placed = n2

    # --- Steps 2+: extend layer by layer ---
    for i in range(2, len(m_layers)):
        n_inner = m_layers[i - 1]
        n_outer = m_layers[i]
        c = n_outer // n_inner

        # Re-embed existing rows onto the n_outer grid by multiplying by c.
        # This maps {0..n_inner-1} → {0, c, 2c, ..., (n_inner-1)*c} ⊂ {0..n_outer-1}.
        X_current = X_current * c   # shape (n_placed, k), now on {0..n_outer-1} subset

        # Build a fresh two-layer design for (n_inner, n_outer).
        # We only need its complement rows — the inner rows tell us the
        # coarse-grid positions but we already have those from X_current.
        X_pair = _two_layer_qian(n_inner, n_outer, k, rng)
        # X_pair rows n_inner..n_outer-1 are on {0..n_outer-1}

        # However the complement rows in X_pair were built relative to
        # X_pair's own inner layer, which differs from X_current's inner
        # layer positions (since X_pair is a fresh independent draw).
        # We cannot use X_pair's complement directly — it would conflict
        # with X_current's occupied slots.
        #
        # Instead: determine the occupied fine-grid levels from X_current,
        # then fill the complement by assigning remaining levels per column
        # independently (each column gets a random permutation of its
        # available levels).  This is valid because the complement rows
        # only need to cover the unoccupied n_outer strata.
        n_new = n_outer - n_inner
        complement = np.zeros((n_new, k), dtype=np.int64)
        for j in range(k):
            used = set(X_current[:, j].tolist())
            available = np.array(
                sorted(x for x in range(n_outer) if x not in used),
                dtype=np.int64,
            )
            assert len(available) == n_new, (
                f"Available levels mismatch at layer {i}, col {j}: "
                f"expected {n_new}, got {len(available)}"
            )
            rng.shuffle(available)
            complement[:, j] = available

        X_current = np.vstack([X_current, complement])

        new_indices = list(range(n_placed, n_placed + n_new))
        layer_indices[n_outer] = layer_indices[n_inner] + new_indices
        n_placed += n_new

    # --- Final re-scale from n_L grid (already on it after last expansion) ---
    # After the last expansion X_current is on {0..n_L-1} — no further scaling needed.
    assert X_current.shape == (n_L, k), (
        f"Shape mismatch: expected ({n_L}, {k}), got {X_current.shape}"
    )

    return X_current, layer_indices


# ---------------------------------------------------------------------------
# Validation helpers (internal)
# ---------------------------------------------------------------------------

def _check_integer_lhd(X: np.ndarray, n: int, indices: list[int]) -> bool:
    """
    Check that rows `indices` of X form a valid LHD on the n-grid.
    Each column must contain exactly one value per stratum of width n_L // n.
    """
    n_L = X.shape[0]
    stride = n_L // n
    sub = X[indices, :]
    for j in range(X.shape[1]):
        coarse = sub[:, j] // stride
        if sorted(coarse.tolist()) != list(range(n)):
            return False
    return True


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def nested_lhd(
    k: int,
    m_layers: list[int] | int,
    seed: int | None = None,
    scramble: bool = True,
    optimise: bool = False,
) -> list[np.ndarray]:
    """
    Construct a multi-layer nested Latin hypercube design using Qian (2009).

    Divisibility constraint: n_{i+1} % n_i == 0 for all consecutive pairs.

    Each column is generated independently via a circulant-matrix walk on the
    lcm grid (Qian 2009, Section 2).  No cross-column row coupling is applied;
    joint uniformity comes from the independent valid-column construction.

    Coordinate convention: zero-indexed strata {0, ..., n-1} converted to
    continuous via (level + u) / n_L where u is drawn once for the full design
    and all inner layers inherit the same u at their row positions.  Strata
    [k/n_L, (k+1)/n_L) tile [0, 1) with no directional edge bias.

    Parameters
    ----------
    k : int
        Number of dimensions. Must be >= 1.
    m_layers : list[int] or int
        Strictly increasing layer sizes; each n_{i+1} must be a multiple of n_i.
        Minimum 2 layers (if int, treated as single-layer, no nesting).
    seed : int or None
        Random seed for reproducibility.
    scramble : bool
        If True (default), u ~ Uniform(0, 1) per cell — genuine randomness within
        each stratum.  If False, u = 0.5 — deterministic midpoint of each stratum.
    optimise : bool
        Reserved for future post-hoc ESE improvement pass.  Currently ignored.

    Returns
    -------
    list of np.ndarray
        layers[i] is (m_layers[i], k) float64 in [0, 1).
        layers[0] ⊂ layers[1] ⊂ ... ⊂ layers[L-1] as exact row subsets.
        Each layers[i] is a valid LHD: one point per stratum [j/n, (j+1)/n)
        in each dimension.

    Raises
    ------
    ValueError
        If m_layers violates the Qian divisibility constraint.

    Examples
    --------
    >>> layers = nested_lhd(k=2, m_layers=[100, 200, 400, 800, 1600], seed=42)
    >>> [layer.shape for layer in layers]
    [(100, 2), (200, 2), (400, 2), (800, 2), (1600, 2)]
    """
    # Handle single-layer degenerate case
    if isinstance(m_layers, int):
        m_layers = [m_layers]
    if len(m_layers) == 1:
        n = m_layers[0]
        rng = np.random.default_rng(seed)
        X_int = random_integer_lhd(n, k, rng)
        u = rng.random((n, k)) if scramble else np.full((n, k), 0.5)
        return [(X_int.astype(float) + u) / n]

    validate_m_layers_qian(m_layers)
    rng = np.random.default_rng(seed)
    n_L = m_layers[-1]

    # --- Build full integer design and layer index map ---
    X_int, layer_indices = _build_multilayer_integer(m_layers, k, rng)

    # --- Internal validation: check each layer is a valid LHD on its own grid ---
    for n in m_layers:
        assert _check_integer_lhd(X_int, n, layer_indices[n]), (
            f"Internal error: layer n={n} failed integer LHD check. "
            "Please report this as a bug."
        )

    # --- Single conversion to continuous: u drawn once, shared across all layers ---
    if scramble:
        u = rng.random((n_L, k))
    else:
        u = np.full((n_L, k), 0.5)

    full = (X_int.astype(np.float64) + u) / n_L

    # --- Extract layers using explicit tracked indices ---
    layers = [full[layer_indices[n], :].copy() for n in m_layers]

    # --- Final validation ---
    validate_result(layers, m_layers, k, convention="stratum", nesting_check="exact")

    return layers